export const postgreConstants = {
    HOST: 'POSTGRES_HOST',
    POSTGRES_PORT: 'POSTGRES_PORT',
    USER: 'POSTGRES_USER',
    PASSWORD: 'POSTGRES_PASSWORD',
    DATABASE: 'POSTGRES_DATABASE',
    PORT: 'PORT',
    MODE: 'MODE',
    RUN_MIGRATIONS: 'RUN_MIGRATIONS'
};